"""PostToolUse hook: the GitHub connector appends a Claude footer server-side, so make the agent remove it."""
import json

print(json.dumps({
	"hookSpecificOutput": {
		"hookEventName": "PostToolUse",
		"additionalContext": (
			"The GitHub connector appends a 'Generated by Claude Code' footer on the server, "
			"which the workspace forbids. Read back what you just wrote (PR body, comment, "
			"review or issue) and rewrite it without the footer before doing anything else."
		),
	}
}))
